name: repo-indexer-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytest
  - black
  - flake8
  - mypy
  - pip:
    - fastapi
    - "typer[all]"
    - sentence-transformers
    - elasticsearch==8.8.0
    - gitpython
    - uvicorn
    - python-dotenv
    - jinja2
    - "openai>=1.0.0"
    - markdown